name: SWG Source - Continuous Integration for src repo

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  compile-src:
    runs-on: ubuntu-latest
    container: cekisswg/swg-vm3.01-i386:latest

    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run ANT Build
        run: |
          cd /home/swg/swg-main/src
          ant build_src
